'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0"), _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()), MySettings)

#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region

        Public Shared ReadOnly Property [Default]() As MySettings
            Get

#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\S2PADM\Printbox\")> _
        Public Property printBox() As String
            Get
                Return CType(Me("printBox"), String)
            End Get
            Set(value As String)
                Me("printBox") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("\\SPHAS30\prescription$\ADMISSION\")> _
        Public Property fldPath() As String
            Get
                Return CType(Me("fldPath"), String)
            End Get
            Set(value As String)
                Me("fldPath") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\S2PADM\flog\")> _
        Public Property logfldroot() As String
            Get
                Return CType(Me("logfldroot"), String)
            End Get
            Set(value As String)
                Me("logfldroot") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\S2PADM\backup\")> _
        Public Property backuproot() As String
            Get
                Return CType(Me("backuproot"), String)
            End Get
            Set(value As String)
                Me("backuproot") = value
            End Set
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "<ArrayOfString xmlns:xsi=""http://www.w3." & _
            "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "  <s" & _
            "tring>C02F_OPH</string>" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "  <string>A05F_OPH</string>" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "  <string>A07F_OPH</string" & _
            ">" & Global.Microsoft.VisualBasic.ChrW(13) & Global.Microsoft.VisualBasic.ChrW(10) & "</ArrayOfString>")> _
        Public ReadOnly Property fldNameList() As Global.System.Collections.Specialized.StringCollection
            Get
                Return CType(Me("fldNameList"), Global.System.Collections.Specialized.StringCollection)
            End Get
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\S2PADM\runtime\")> _
        Public Property runtimeroot() As String
            Get
                Return CType(Me("runtimeroot"), String)
            End Get
            Set(value As String)
                Me("runtimeroot") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Sumatra\sumatrapdf.exe")> _
        Public Property pdfviewerpath() As String
            Get
                Return CType(Me("pdfviewerpath"), String)
            End Get
            Set(value As String)
                Me("pdfviewerpath") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("\\SPHIS51\AGADMR1")> _
        Public Property printerName1() As String
            Get
                Return CType(Me("printerName1"), String)
            End Get
            Set(value As String)
                Me("printerName1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("\\SPHAS30\prescription$\ADMISSION\")> _
        Public Property OUbkpath() As String
            Get
                Return CType(Me("OUbkpath"), String)
            End Get
            Set(value As String)
                Me("OUbkpath") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("_BKUP")> _
        Public Property OUbksuffix() As String
            Get
                Return CType(Me("OUbksuffix"), String)
            End Get
            Set(value As String)
                Me("OUbksuffix") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("60000")> _
        Public Property taskfrq() As Integer
            Get
                Return CType(Me("taskfrq"), Integer)
            End Get
            Set(value As Integer)
                Me("taskfrq") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\CPDF\cpdf.exe")> _
        Public Property cpdfpath() As String
            Get
                Return CType(Me("cpdfpath"), String)
            End Get
            Set(value As String)
                Me("cpdfpath") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\S2PADM\Printbox\log\")> _
        Public Property printboxlogfld() As String
            Get
                Return CType(Me("printboxlogfld"), String)
            End Get
            Set(value As String)
                Me("printboxlogfld") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("\\SPHIS50")> _
        Public Property printServer1() As String
            Get
                Return CType(Me("printServer1"), String)
            End Get
            Set(value As String)
                Me("printServer1") = value
            End Set
        End Property

        <Global.System.Configuration.UserScopedSettingAttribute(), _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
         Global.System.Configuration.DefaultSettingValueAttribute("A02PHARFAXB2")> _
        Public Property printQueue1() As String
            Get
                Return CType(Me("printQueue1"), String)
            End Get
            Set(value As String)
                Me("printQueue1") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My

    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
    Friend Module MySettingsProperty

        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")> _
        Friend ReadOnly Property Settings() As Global.S2PADM.My.MySettings
            Get
                Return Global.S2PADM.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
